from turtle import *
x1 = int(input("Enter the x coordinates of the center for square 1: "))
y1 = int(input("Enter the y coordinates of the center for square 1: "))
l1 = int(input("Enter the Lenght for square 1: "))
w1 = int(input("Enter the Width for square 1: "))
x2 = int(input("Enter the x coordinates of the center for square 2: "))
y2 = int(input("Enter the y coordinates of the center for square 2: "))
l2 = int(input("Enter the Lenght for square 2: "))
w2 = int(input("Enter the Width for square 2: "))
overlap = False
amount = 0
top_left1x = (x1 - l1/2)
top_left1y = (y1 + w1/2)
top_right1x = (x1 + l1/2)
top_right1y = (y1 + w1/2)
bottom_left1x = (x1 - l1/2)
bottom_left1y = (y1 - w1/2)
bottem_right1x = (x1 + l1/2)              
bottom_right1y =(y1 - w1/2)
top_left2x = (x2 - l2/2)
top_left2y = (y2 + w2/2)
top_right2x = (x2 + l2/2)
top_right2y = (y2 + w2/2)
bottom_left2x = (x2 - l2/2)
bottom_left2y = (y2 - w2/2)
bottem_right2x = (x2 + l2/2)              
bottom_right2y =(y2 - w2/2)
if top_right1x > top_right2x and top_left1x < top_left2x and top_left1y > top_left2y and bottom_left1y < bottom_right2y:
    print("It is inside")
elif top_right2x > top_right1x and top_left2x < top_left1x and top_left2y > top_left1y and bottom_left2y < bottom_right1y:
    print("It is inside")
elif top_right1x < top_left2x or top_left1y < bottom_left2y or top_left1x > top_right2x or bottom_left1y >top_left2y:
    print("It does not overlap") 
else:
    print("it overlaps")
penup()
goto(x1,y1)
pendown()
circle(1)
penup()
p = pos()
write(p)
goto(top_left1x,top_left1y)
pendown()
goto(top_right1x,top_right1y)
goto(bottem_right1x,bottom_right1y)
goto(bottom_left1x,bottom_left1y)
goto(top_left1x,top_right1y)
penup()
goto(x2,y2)
pendown()
circle(1)
penup()
p = pos()
write(p)
goto(top_left2x,top_left2y)
pendown()
goto(top_right2x,top_right2y)
goto(bottem_right2x,bottom_right2y)
goto(bottom_left2x,bottom_left2y)
goto(top_left2x,top_right2y)
done()
